module HanzoAI
  class Error < StandardError
    attr_accessor cause: StandardError?
  end

  class ConversionError < HanzoAI::Error
  end

  class APIError < HanzoAI::Error
    attr_accessor url: URI::Generic

    attr_accessor status: Integer?

    attr_accessor body: top?

    def initialize: (
      url: URI::Generic,
      ?status: Integer?,
      ?body: Object?,
      ?request: nil,
      ?response: nil,
      ?message: String?
    ) -> void
  end

  class APIConnectionError < HanzoAI::APIError
    def initialize: (
      url: URI::Generic,
      ?status: nil,
      ?body: nil,
      ?request: nil,
      ?response: nil,
      ?message: String?
    ) -> void
  end

  class APITimeoutError < HanzoAI::APIConnectionError
    def initialize: (
      url: URI::Generic,
      ?status: nil,
      ?body: nil,
      ?request: nil,
      ?response: nil,
      ?message: String?
    ) -> void
  end

  class APIStatusError < HanzoAI::APIError
    def self.for: (
      url: URI::Generic,
      status: Integer,
      body: Object?,
      request: nil,
      response: nil,
      ?message: String?
    ) -> instance

    def initialize: (
      url: URI::Generic,
      status: Integer,
      body: Object?,
      request: nil,
      response: nil,
      ?message: String?
    ) -> void
  end

  class BadRequestError < HanzoAI::APIStatusError
    HTTP_STATUS: 400
  end

  class AuthenticationError < HanzoAI::APIStatusError
    HTTP_STATUS: 401
  end

  class PermissionDeniedError < HanzoAI::APIStatusError
    HTTP_STATUS: 403
  end

  class NotFoundError < HanzoAI::APIStatusError
    HTTP_STATUS: 404
  end

  class ConflictError < HanzoAI::APIStatusError
    HTTP_STATUS: 409
  end

  class UnprocessableEntityError < HanzoAI::APIStatusError
    HTTP_STATUS: 422
  end

  class RateLimitError < HanzoAI::APIStatusError
    HTTP_STATUS: 429
  end

  class InternalServerError < HanzoAI::APIStatusError
    HTTP_STATUS: Range[Integer]
  end
end
