module Hanzoai
  class Error < StandardError
    attr_accessor cause: StandardError?
  end

  class ConversionError < Hanzoai::Error
  end

  class APIError < Hanzoai::Error
    attr_accessor url: URI::Generic

    attr_accessor status: Integer?

    attr_accessor body: top?

    def initialize: (
      url: URI::Generic,
      ?status: Integer?,
      ?body: Object?,
      ?request: nil,
      ?response: nil,
      ?message: String?
    ) -> void
  end

  class APIConnectionError < Hanzoai::APIError
    def initialize: (
      url: URI::Generic,
      ?status: nil,
      ?body: nil,
      ?request: nil,
      ?response: nil,
      ?message: String?
    ) -> void
  end

  class APITimeoutError < Hanzoai::APIConnectionError
    def initialize: (
      url: URI::Generic,
      ?status: nil,
      ?body: nil,
      ?request: nil,
      ?response: nil,
      ?message: String?
    ) -> void
  end

  class APIStatusError < Hanzoai::APIError
    def self.for: (
      url: URI::Generic,
      status: Integer,
      body: Object?,
      request: nil,
      response: nil,
      ?message: String?
    ) -> instance

    def initialize: (
      url: URI::Generic,
      status: Integer,
      body: Object?,
      request: nil,
      response: nil,
      ?message: String?
    ) -> void
  end

  class BadRequestError < Hanzoai::APIStatusError
    HTTP_STATUS: 400
  end

  class AuthenticationError < Hanzoai::APIStatusError
    HTTP_STATUS: 401
  end

  class PermissionDeniedError < Hanzoai::APIStatusError
    HTTP_STATUS: 403
  end

  class NotFoundError < Hanzoai::APIStatusError
    HTTP_STATUS: 404
  end

  class ConflictError < Hanzoai::APIStatusError
    HTTP_STATUS: 409
  end

  class UnprocessableEntityError < Hanzoai::APIStatusError
    HTTP_STATUS: 422
  end

  class RateLimitError < Hanzoai::APIStatusError
    HTTP_STATUS: 429
  end

  class InternalServerError < Hanzoai::APIStatusError
    HTTP_STATUS: Range[Integer]
  end
end
